#
#   ghack.
#   Copyright (C) 1999-2010 Neil McGill
#
#   This game is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Library General Public
#   License as published by the Free Software Foundation; either
#   version 2 of the License, or (at your option) any later version.
#
#   This game is distributed in the hope that it will be fun,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License along with this game; if not, write to the Free
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   Neil McGill
#
#   $Id: Makefile.in 1275 2009-08-07 13:01:53Z Goblinhack $
#

TOP=../..

include $(TOP)/build/mk/config

OBJS =\
	hiscore.o \
	read_text.o \
	read_small_text.o \
	help_txt.o \
	intro.o \
	level_chooser.o \
	config.o \
	player_chooser.o \
	player_class_chooser.o \
	level_type_chooser.o \
	player_powerup_chooser.o \
	player_auto_save.o \
	level_end.o \
	level_start.o \
	messages.o \
	player_croaked_it.o \
	player_dead.o \

TARGET = $(TOP)/src/ghack

include $(TOP)/build/mk/library
