#
#   ghack.
#   Copyright (C) 1999-2010 Neil McGill
#
#   This game is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Library General Public
#   License as published by the Free Software Foundation; either
#   version 2 of the License, or (at your option) any later version.
#
#   This game is distributed in the hope that it will be fun,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License along with this game; if not, write to the Free
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   Neil McGill
#
#   $Id: Makefile.in 1297 2009-08-24 13:50:50Z Goblinhack $
#

TOP=../..

include $(TOP)/build/mk/config

OBJS =\
	audio.o \
	actions.o \
	anger.o \
	possess.o \
	anim.o \
	armour.o \
	ability.o \
	water_proof.o \
	fire_proof.o \
	acid_proof.o \
	cold_proof.o \
	suffocation_proof.o \
	teleport_proof.o \
	poison_proof.o \
	stone_proof.o \
	attack.o \
	polymorph.o \
	bite.o \
	can_see_distance.o \
	chasing.o \
	collect.o \
	collision.o \
	dead.o \
	debug.o \
	default.o \
	drop.o \
	bravery.o \
	find.o \
	followers.o \
	gfx.o \
	hit.o \
	item.o \
	insult.o \
	util.o \
	lifespan.o \
	light_strength.o \
	log.o \
	meet.o \
	exit.o \
	metabolism.o \
	monst.o \
	move.o \
	open.o \
	parse.o \
	ref.o \
	ptr.o \
	registration.o \
	room.o \
	scared.o \
	shop.o \
	sleeping.o \
	shielded.o \
	invisible.o \
	poisoned.o \
	stone.o \
	spawn.o \
	summon.o \
	spell.o \
	strength.o \
	dex.o \
	stamina.o \
	teleport.o \
	rage.o \
	thing.o \
	unique_things.o \
	throwing.o \
	tick.o \
	transmog.o \
	use.o \
	vision.o \
	weapon.o \
	wear.o \

TARGET = $(TOP)/src/ghack

include $(TOP)/build/mk/library
